### PR TITLE
Update resize-img@2.0.0

### PR DESCRIPTION
**Pull request by thisconnect**

### CODE REVIEW

**Comment by pft** [comment]
The checks fail because the use of async functions and the NodeJS versions targeted by travis.yml (4 and 6). Async functions are available without flags from NodeJS version 8 onwards.

**Comment by thisconnect** [comment]
> The checks fail because the use of async functions and the NodeJS versions targeted by travis.yml (4 and 6). Async functions are available without flags from NodeJS version 8 onwards.

yes and therefore I'd love your PR https://github.com/kevva/to-ico/pull/23 :)

**Comment by Tofandel** [comment]
@kevva A deps update is long overdue, getting tons of deprecation warning on install, please :pray:

**Comment by ebonow** [comment]
Please escalate this. Currently, `to-ico` is a dependency of `favicons` and all of its users (including myself) are failing security [audits](https://www.npmjs.com/advisories/1550)


Screen Shot 2021-04-24 at 11 56 08 AM

**Comment by chevEldrid** [comment]
just ran into the same issue with url-regex that led me here, seems to be becoming an increasingly large problem

**Comment by DavidHalman** [comment]
Also ran into this issue, I would love a fix soon!

**Review by jimmywarting — APPROVED** [review]

**Comment by NJAldwin** [comment]
For anyone else finding this issue causing audit failures: you can update to `png-to-ico`, which seems to be a drop-in replacement for `to-ico` without this vulnerability.

This is what `favicons` has done: https://github.com/itgalaxy/favicons/pull/337

**Pull request closed without merging**
