### PR TITLE
Document unsupported formats

### PR DESCRIPTION
**Pull request by gianluca-nitti**
After failing to convert a png to ico (I was getting an ico with pixels of random colors), I did some research and I found out that my image was in the indexed colormap format (8 bits per _pixel_), while [pngjs only supports 8 bits per _channel_ depth](https://github.com/niegowski/node-pngjs#documentation). I suggest adding this to the readme so users can find this out without needing to digg in the documentation of the underlying modules.

### CODE REVIEW

**Comment by jdalton** [comment]
I hit this and was wondering why I had a corrupt ico. This explains it.

**Comment by sindresorhus** [comment]
Merging this, but we should really find a better PNG encoder/decoder: https://github.com/kevva/to-ico/issues/16

**Comment by kevva** [comment]
Some of this is incorrect. First and foremost, we're not using the linked module, but https://github.com/lukeapage/pngjs, which does [support interlacing](https://github.com/kevva/parse-png/blob/master/test.js#L21-L29). Indexed color is still unsupported though.

**Comment by gianluca-nitti** [comment]
> First and foremost, we're not using the linked module, but https://github.com/lukeapage/pngjs

Oh I see now, sorry for the misunderstanding. Most likely I got confused by the two modules having very similar names on npm (`pngjs` and `node-pngjs`).

**Comment by kevva** [comment]
No worries, it's understandable since there are a lot of forks of it with similar names :).

**Pull request merged**
